"use client";
import {useState,useEffect,useRef,useCallback} from "react";
import {flushSync} from "react-dom";
import {ArrowUpRight,ArrowRight,ScanLine,ChevronRight,FlaskConical,Info,Wallet,ExternalLink,Download,Loader2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from "@/components/ui/table";
import {demoReport} from "@/lib/demo";
import {short,percent,money,formatDelay,type Report,type Position} from "@/lib/analysis";
import {validateRequest} from "@/lib/coingecko";
type Form={leader:string;follower:string;from:string;to:string};
type ModelTool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown};
type Context={registerTool:(tool:ModelTool,options:{signal:AbortSignal})=>void|Promise<void>};
const today=()=>new Date().toISOString().slice(0,10);
const weekAgo=()=>new Date(Date.now()-6*86400000).toISOString().slice(0,10);
const pp=(n:number|null)=>n===null?"—":(n>=0?"+":"−")+Math.abs(n).toFixed(1);
const positionReturn=(p:Position|null)=>!p?"—":p.returnPct!==null?percent(p.returnPct):p.status==="partial"?"Partial":p.status==="open"?"Open":"Review";
export default function Home(){
 const [report,setReport]=useState<Report>(()=>demoReport());
 const [selected,setSelected]=useState("demo-ORBIT");
 const [form,setForm]=useState<Form>({leader:"",follower:"",from:weekAgo(),to:today()});
 const [configured,setConfigured]=useState<boolean|null>(null);
 const [error,setError]=useState("");
 const [busy,setBusy]=useState(false);
 const lock=useRef(false);
 const state=useRef({report,form});state.current={report,form};
 useEffect(()=>{fetch("/api/status",{cache:"no-store"}).then(r=>r.json() as Promise<{configured:boolean}>).then(r=>setConfigured(Boolean(r.configured))).catch(()=>setConfigured(null));},[]);
 const loadDemo=useCallback(()=>{if(lock.current)throw new Error("Wait for the current comparison to finish.");const next=demoReport();flushSync(()=>{setReport(next);setSelected(next.rows[0].token);setError("");});return{mode:"demo",tokens:next.rows.length,comparable:next.comparableCount};},[]);
 const compareWallets=useCallback(async(input:Form)=>{
  if(lock.current)throw new Error("A comparison is already running.");
  try{validateRequest(input);}catch(e){const message=e instanceof Error?e.message:"Invalid input.";setError(message);throw new Error(message);}
  lock.current=true;setBusy(true);setError("");setForm(input);
  try{
   const response=await fetch("/api/compare",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input),signal:AbortSignal.timeout(35000)});
   const data=await response.json() as Report & {error?:string};
   if(!response.ok)throw new Error(data.error||"The comparison could not be completed.");
   const next=data as Report;
   flushSync(()=>{setReport(next);setSelected(next.rows[0]?.token||"");});
   return{mode:next.mode,tokens:next.rows.length,comparable:next.comparableCount,gapPercentagePoints:next.gap};
  }catch(e){const message=e instanceof Error&&e.name!=="TimeoutError"?e.message:"The request timed out. Please try again.";setError(message);throw new Error(message);}
  finally{lock.current=false;setBusy(false);}
 },[]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:Context}).modelContext;if(!context)return;
  const lifecycle=new AbortController();
  const register=(tool:ModelTool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};
  register({name:"load_demo_review",description:"Load the fictional CopyCheck example into the visible dashboard. No external data request.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("Expected an empty object.");return loadDemo();}});
  register({name:"compare_wallets",description:"Compare observed Solana swaps for two public wallets and show the review. Sends those addresses and dates to the CoinGecko-backed server. Requires live API configuration.",inputSchema:{type:"object",properties:{leader:{type:"string"},follower:{type:"string"},from:{type:"string",description:"UTC YYYY-MM-DD"},to:{type:"string",description:"UTC YYYY-MM-DD"}},required:["leader","follower","from","to"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){validateRequest(input);return compareWallets(input as Form);}});
  register({name:"get_current_review",description:"Read the currently visible CopyCheck review, including whether it is synthetic demo data.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("Expected an empty object.");const r=state.current.report;return{mode:r.mode,from:r.from,to:r.to,comparable:r.comparableCount,gapPercentagePoints:r.gap,rows:r.rows.map(t=>({token:t.token,finding:t.finding,comparable:t.comparable}))};}});
  return()=>lifecycle.abort();
 },[loadDemo,compareWallets]);
 const row=report.rows.find(r=>r.token===selected);
 const update=(key:keyof Form,value:string)=>setForm(f=>({...f,[key]:value}));
 const exportReport=()=>{const blob=new Blob([JSON.stringify(report,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download="copycheck-"+report.mode+"-"+report.from+".json";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const incomplete=!report.coverage.leader.complete||!report.coverage.follower.complete||report.coverage.leader.skipped>0||report.coverage.follower.skipped>0;
 return <><header><a href="/" className="brand"><ScanLine/>CopyCheck <small>BETA</small></a><span className="nav-active">Trade review</span><a href="#method">How it works <ArrowUpRight size={14}/></a></header><main>
 <div className="heading"><div><div className="eyebrow">THE TRADE AFTER THE TRADE</div><h1>Same trade. Different result.</h1><p>Find the gap between the wallet you followed and the trade you got.</p></div><span className="pill">● Solana</span></div>
 <form className="compare-box" onSubmit={e=>{e.preventDefault();void compareWallets(form).catch(()=>{});}} aria-label="Compare two wallets">
 <div className="fields"><label><span><Wallet size={15}/>Wallet you followed</span><Input value={form.leader} onChange={e=>update("leader",e.target.value.trim())} placeholder="Paste a public Solana address" maxLength={44} spellCheck={false} autoComplete="off" required disabled={busy}/></label><ArrowRight size={20}/><label><span><Wallet size={15}/>Your wallet</span><Input value={form.follower} onChange={e=>update("follower",e.target.value.trim())} placeholder="Paste your public Solana address" maxLength={44} spellCheck={false} autoComplete="off" required disabled={busy}/></label><Button disabled={busy} type="submit">{busy?<><Loader2 className="animate-spin"/>Comparing…</>:<>Compare wallets <ArrowRight size={16}/></>}</Button></div>
 <div className="dates"><label>From<Input aria-label="Start date" type="date" value={form.from} onChange={e=>update("from",e.target.value)} max={form.to||today()} disabled={busy} required/></label><label>To<Input aria-label="End date" type="date" value={form.to} onChange={e=>update("to",e.target.value)} min={form.from} max={today()} disabled={busy} required/></label><span className="status">{configured===true?"● Live data connected":configured===false?"○ Live data needs an API key":"○ Checking live connection"}</span></div>
 <div className="form-footer"><span>Read-only · UTC dates · 30-day maximum</span><Button variant="ghost" type="button" size="sm" disabled={busy} onClick={()=>loadDemo()}><FlaskConical size={14}/>Try an example</Button></div><p className="privacy-note">Comparing sends these public addresses to CoinGecko. No wallet connection or signing.</p></form>
 {error&&<div role="alert" className="error-banner"><strong>Comparison not completed.</strong> {error}<br/><span>The review below is the previous {report.mode==="demo"?"fictional example":"successful comparison"}.</span></div>}
 {report.mode==="demo"?<div className="demo-banner"><FlaskConical size={17}/><span><strong>You’re exploring a sample review.</strong> Fictional tokens and trades, real comparison logic.</span><small>DEMO DATA</small></div>:<div className="demo-banner"><Info size={17}/><span><strong>Observed wallet trades.</strong> Leader {short(report.leaderWallet)} · You {short(report.followerWallet)}</span><small>COINGECKO DATA</small></div>}
 <div className="review-heading"><h2>Your trade review <small>{report.rows.length} tokens</small></h2><div className="actions"><span className="status">{report.from} {report.to!==report.from?"→ "+report.to:""} · UTC</span><Button size="sm" variant="outline" onClick={exportReport}><Download size={14}/>Export</Button></div></div>
 <div className="metrics" aria-live="polite"><section><span>Leader’s average return</span><strong className="leader">{percent(report.leaderAverage)}</strong><p>Across {report.comparableCount} comparable closed positions</p></section><section><span>Your average return</span><strong className="follower">{percent(report.followerAverage)}</strong><p>Equal weight per comparable token</p></section><section><span>The performance gap</span><strong>{pp(report.gap)} <small>pp</small></strong><p>Before gas, tips and platform fees · pp = percentage points</p></section></div>
 {incomplete&&<p className="coverage" role="status">History is incomplete: {report.coverage.leader.pages} leader pages, {report.coverage.follower.pages} follower pages; {report.coverage.leader.skipped+report.coverage.follower.skipped} unusable records. Returns are withheld. Try a shorter period.</p>}
 <div className="workspace"><section className="panel"><div className="panel-heading"><h2>Follow the difference</h2><small>SELECT A TOKEN</small></div>{report.rows.length?<Table><TableHeader><TableRow><TableHead>Token</TableHead><TableHead>Leader</TableHead><TableHead>You</TableHead><TableHead>Finding</TableHead><TableHead><span className="sr-only">Details</span></TableHead></TableRow></TableHeader><TableBody>{report.rows.map((t,i)=><TableRow key={t.token} className={selected===t.token?"selected":""}><TableCell><Button variant="ghost" className="token-button" aria-label={"Review "+t.label} aria-pressed={selected===t.token} onClick={()=>setSelected(t.token)}><span className={"token-icon token-"+i%4}>{t.label[0]}</span><span>{t.label}<small>{report.mode==="demo"?"Sample token":"Solana token"}</small></span></Button></TableCell><TableCell className="leader">{incomplete?"—":positionReturn(t.leader)}</TableCell><TableCell>{incomplete?"—":positionReturn(t.follower)}</TableCell><TableCell><span className="chip">{t.finding}</span></TableCell><TableCell><ChevronRight size={15}/></TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><h3>No swaps found in this period.</h3><p>Check the wallets and dates. A missing record does not prove a trade failed.</p></div>}<div className="panel-foot"><Info size={14}/>Matches suggest a connection; they do not prove copy intent.</div></section>
 {row?<aside className="panel detail" aria-live="polite"><div className="panel-heading"><h2>{row.label} breakdown</h2><span className="chip">{row.comparable?"Candidate match":"Needs review"}</span></div><div className="insight"><span className="icon">{row.comparable?"↗":"!"}</span><h3>{row.title}</h3><p>{row.explanation}</p></div>
 <Tabs defaultValue="prices" key={row.token}><TabsList><TabsTrigger value="prices">Price comparison</TabsTrigger><TabsTrigger value="evidence">Evidence</TabsTrigger></TabsList><TabsContent value="prices"><div className="legend"><span className="leader">● Leader</span><span className="follower">● You</span></div><div className="bars">{[["Average entry",row.leader?.entry??null,row.follower?.entry??null],["Average exit",row.leader?.exit??null,row.follower?.exit??null]].map(([label,l,f])=>{const max=Math.max(Number(l)||0,Number(f)||0)*1.1;return <div key={String(label)}><span>{label}</span>{[{v:l,c:"leader"},{v:f,c:"follower"}].map(({v,c})=><div key={c} className={"bar "+c+"-bar"} style={{width:v===null?"25%":Math.max(25,Number(v)/max*100)+"%"}}>{money(v as number|null)}</div>)}</div>;})}</div>
 {row.comparable&&<><div className="effects"><div><span>Entry-price effect</span><strong>{pp(row.entryEffect)} pp</strong></div><div><span>Exit-price effect</span><strong>{pp(row.exitEffect)} pp</strong></div></div><p className="note">Together these explain the {pp(row.gap)} pp return gap. This is a price decomposition, not proof of what caused it.</p></>}
 <p className="note">Observed fill averages in USD. Partial exits are not full-position returns. No market-price chart or live balance is implied.</p></TabsContent><TabsContent value="evidence"><p className="coverage">First buy: {formatDelay(row.entryDelay)}<br/>Last sale: {formatDelay(row.exitDelay)}<br/>Relative to the leader’s block timestamps.</p>{report.mode==="live"&&<p className="address">Token: {row.token}</p>}<div className="evidence">{[{name:"Leader",p:row.leader},{name:"You",p:row.follower}].flatMap(({name,p})=>(p?.trades||[]).map(t=><div className="evidence-row" key={name+t.id}><div><strong>{name} · {t.side==="buy"?"Bought":"Sold"}</strong><small>{t.quantity.toLocaleString("en-US",{maximumSignificantDigits:6})} tokens · {money(t.usd)} total</small><small>{new Date(t.time).toISOString().replace("T"," ").replace(".000Z"," UTC")}</small></div>{report.mode==="live"?<a href={"https://solscan.io/tx/"+encodeURIComponent(t.tx)} target="_blank" rel="noreferrer" aria-label={"View "+name+" "+t.side+" transaction"}>Tx <ExternalLink size={12}/></a>:<span className="note">Synthetic</span>}</div>))}</div><p className="note" style={{marginTop:12}}>Gas, priority tips and bot/platform fees are unavailable from this endpoint. Timing is an observed block-time difference, not measured bot latency.</p></TabsContent></Tabs></aside>:<aside className="panel empty">A breakdown will appear when matching data is available.</aside>}</div>
 <section id="method" className="method"><h3><Info size={18}/>Evidence first. No guesswork disguised as certainty.</h3><p>CopyCheck groups swaps by exact token address. It compares a single observed position when both wallets close it, and your first buy is within 30 minutes after the leader’s. This is a matching rule, not proof of copy intent. Separate round trips, uncertain ordering, missing buys and incomplete history are excluded from the headline figures.</p><p>Gross return = (average exit price ÷ average entry price − 1) × 100. The headline is an equally weighted average across eligible tokens, not a portfolio return. Entry-price effect holds the leader’s exit price fixed; exit-price effect then uses your entry price. CopyCheck computes these figures; CoinGecko supplies the observed trade data.</p><p>Transfers, prior inventory, untracked venues, gas and bot fees can change the real result. Timing alone cannot identify slippage, a bot failure or market movement. This tool reviews past executions; it does not recommend trades.</p></section>
 <footer><span>CopyCheck <span className="muted">/ A little clarity after the trade.</span></span><a href="https://www.coingecko.com/en/api" target="_blank" rel="noreferrer">Live data integration: CoinGecko API ↗</a></footer></main></>;
}
