"use client";
import {useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {holdingResult,validQuote,type Quote} from '@/lib/holdings';
type Row={key:number;id:string;quantity:string;cost:string};
const usd=(n:number|null)=>n===null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const pct=(n:number|null)=>n===null?'—':(n>0?'+':'')+n.toFixed(1)+'%';
const coins:Record<string,string>={bitcoin:'Bitcoin (BTC)',ethereum:'Ethereum (ETH)',solana:'Solana (SOL)',hyperliquid:'Hyperliquid (HYPE)',binancecoin:'BNB',ripple:'XRP',dogecoin:'Dogecoin (DOGE)',cardano:'Cardano (ADA)',chainlink:'Chainlink (LINK)','avalanche-2':'Avalanche (AVAX)',sui:'Sui (SUI)',tether:'Tether (USDT)','usd-coin':'USDC'};
export default function Holdings({onReview,onCompare}:{onReview:()=>void;onCompare:()=>void}){
 const [rows,setRows]=useState<Row[]>([{key:1,id:'bitcoin',quantity:'',cost:''}]),[quotes,setQuotes]=useState<Record<string,Quote>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[demo,setDemo]=useState(false),[exampleAmounts,setExampleAmounts]=useState(false),[change,setChange]=useState(0);
 const update=(key:number,field:keyof Omit<Row,'key'>,value:string)=>{setRows(rs=>rs.map(r=>r.key===key?{...r,[field]:value}:r));};
 const parsed=rows.map(r=>{const quantity=Number(r.quantity),cost=r.cost.trim()===''?null:Number(r.cost),q=quotes[r.id];return {...r,result:r.quantity.trim()!==''&&quantity>0&&Number.isFinite(quantity)&&(cost===null||Number.isFinite(cost)&&cost>=0)&&q&&(demo||validQuote(q))?holdingResult({id:r.id,quantity,cost},q.usd,change):null};});
 const complete=parsed.every(r=>r.result!==null),total=complete?parsed.reduce((s,r)=>s+r.result!.value,0):null,costKnown=complete&&parsed.every(r=>r.result!.cost!==null),cost=costKnown?parsed.reduce((s,r)=>s+r.result!.cost!,0):null;
 const refresh=async()=>{if(busy)return;if(rows.some(r=>!/^[-a-z0-9]{1,80}$/.test(r.id)||r.quantity.trim()===''||!Number.isFinite(Number(r.quantity))||Number(r.quantity)<=0||r.cost!==''&&(!Number.isFinite(Number(r.cost))||Number(r.cost)<0))){setError('Enter a coin ID, a positive amount held and an optional non-negative average purchase price.');return;}setBusy(true);setError('');try{const response=await fetch('/api/prices?ids='+encodeURIComponent([...new Set(rows.map(r=>r.id))].join(',')));const body=await response.json() as {prices:Record<string,Quote>;missing:string[];error?:string};if(!response.ok)throw new Error(body.error);setQuotes(body.prices);setDemo(false);if(body.missing.length)setError('No fresh price for: '+body.missing.join(', ')+'. Check the CoinGecko IDs. Totals stay hidden until every holding has a price.');}catch(e){setQuotes({});setDemo(false);setError(e instanceof Error?e.message:'Prices could not be loaded.');}finally{setBusy(false);}};
 const example=()=>{setRows([{key:1,id:'bitcoin',quantity:'0.1',cost:'70000'},{key:2,id:'ethereum',quantity:'2',cost:'3500'},{key:3,id:'solana',quantity:'20',cost:'180'}]);setQuotes({bitcoin:{usd:80000,last_updated_at:0},ethereum:{usd:3000,last_updated_at:0},solana:{usd:150,last_updated_at:0}});setDemo(true);setExampleAmounts(true);setError('');setChange(0);};
 return <><main>
 <div className='heading'><div><div className='eyebrow'>YOUR CRYPTO, IN DOLLARS</div><h1>See where you stand.</h1><p>Check your holdings, your gains and losses, and the price you need to break even.</p></div><div className='data-brand'><a href='https://www.coingecko.com/en/api' target='_blank' rel='noreferrer'><span>Built with</span><img src='/coingecko-api-logo.svg' alt='CoinGecko API' width='200' height='35'/></a></div></div>
 <section className='panel holdings-form'><div className='panel-heading'><h2>Add what you hold</h2><Button variant='ghost' onClick={example} disabled={busy}>Try an example</Button></div><p className='note'>Works with coins held on an exchange or in a wallet. Enter the amount you still own and its average purchase price in USD. Leave purchase price blank if you don’t know it.</p>
 {rows.map((r,i)=><div className='holding-inputs' key={r.key}><label>Coin<select aria-label={'Coin '+(i+1)} value={coins[r.id]?r.id:'other'} onChange={e=>update(r.key,'id',e.target.value==='other'?'':e.target.value)} disabled={busy}>{Object.entries(coins).map(([id,name])=><option key={id} value={id}>{name}</option>)}<option value='other'>Another coin</option></select>{!coins[r.id]&&<Input aria-label={'CoinGecko ID '+(i+1)} value={r.id} onChange={e=>update(r.key,'id',e.target.value.trim().toLowerCase())} placeholder='CoinGecko API ID' disabled={busy}/>}</label><label>Amount held<Input type='number' min='0' step='any' aria-label={'Amount '+(i+1)} value={r.quantity} onChange={e=>update(r.key,'quantity',e.target.value)} placeholder='0.1' disabled={busy}/></label><label>Average purchase price ($)<Input type='number' min='0' step='any' aria-label={'Purchase price '+(i+1)} value={r.cost} onChange={e=>update(r.key,'cost',e.target.value)} placeholder='Optional' disabled={busy}/></label><Button variant='ghost' aria-label={'Remove holding '+(i+1)} disabled={rows.length===1||busy} onClick={()=>setRows(rs=>rs.filter(x=>x.key!==r.key))}><Trash2 size={16}/></Button></div>)}
 <div className='form-footer'><Button variant='outline' disabled={rows.length>=10||busy} onClick={()=>setRows(rs=>[...rs,{key:Date.now(),id:'',quantity:'',cost:''}])}><Plus size={16}/>Add holding</Button><Button onClick={()=>void refresh()} disabled={busy}>{busy?'Checking prices…':'Check current prices'}</Button></div><p className='note'>Choose a suggested coin or use the API ID shown on its CoinGecko page. Up to 10 entries. Amounts and purchase prices stay in this tab; only coin IDs are sent for prices. Reloading clears your entries.</p></section>
 {error&&<p className='error-banner' role='alert'>{error}</p>}{exampleAmounts&&<div className='demo-banner'><strong>{demo?'Illustrative example · invented holdings and prices.':'Example amounts · current CoinGecko prices.'}</strong> These amounts are illustrative, not a real person’s wallet. Edit them to check your own holdings.</div>}
 <div className='metrics holdings-metrics'><section><span>Value of entered holdings</span><strong>{usd(total)}</strong><p>{complete?'All entered amounts have prices':'Add amounts and check prices to see a total'}</p></section><section><span>Unrealized gain / loss</span><strong className={total!==null&&cost!==null&&total-cost<0?'follower':'leader'}>{total!==null&&cost!==null?usd(total-cost):'—'}</strong><p>{cost!==null&&cost>0&&total!==null?pct((total/cost-1)*100)+' on entered purchase cost':'Needs a purchase price for every holding'}</p></section><section><span>Largest holding</span><strong className='holding-largest'>{complete&&total!==null&&total>0?(coins[[...parsed].sort((a,b)=>b.result!.value-a.result!.value)[0].id]||[...parsed].sort((a,b)=>b.result!.value-a.result!.value)[0].id):'—'}</strong><p>{complete&&total!==null&&total>0?(Math.max(...parsed.map(r=>r.result!.value))/total*100).toFixed(1)+'% of entered value':'Allocation is based on current value'}</p></section></div>
 <section className='panel'><div className='panel-heading'><h2>Your holdings at a glance</h2></div><div className='review-table-scroll'><table><thead><tr><th>Coin</th><th>Price</th><th>Value</th><th>Gain / loss</th><th>Break-even price</th><th>Move to break even</th></tr></thead><tbody>{parsed.map(r=><tr key={r.key}><td>{coins[r.id]||r.id||'Choose a coin'}</td><td>{r.result?usd(quotes[r.id].usd):'—'}</td><td>{usd(r.result?.value??null)}</td><td className={(r.result?.pnl??0)<0?'follower':'leader'}>{usd(r.result?.pnl??null)}</td><td>{usd(r.result?.breakeven??null)}</td><td>{pct(r.result?.recoveryPct??null)}</td></tr>)}</tbody></table></div><div className='panel-foot'>Break-even uses your entered average purchase price. A negative move means the quoted price is already above it. Fees, taxes, slippage and previous sales are not included.</div></section>
 {!demo&&complete&&<p className='note'>CoinGecko quote times: {[...new Set(rows.map(r=>r.id))].map(id=>id+' '+new Date(quotes[id].last_updated_at*1000).toISOString().replace('T',' ').replace('.000Z',' UTC')).join(' · ')}. Quotes older than 15 minutes require a refresh.</p>}
 <section className='panel scenario'><div><h2>Try a market move</h2><p>If every entered coin moved by the same percentage, your holdings would be worth:</p><strong>{total===null?'—':usd(total*(1+change/100))}</strong><p className='note'>Hypothetical, not a forecast. Your amounts stay fixed.</p></div><label>Price move: {pct(change)}<input aria-label='Hypothetical price move' type='range' min='-50' max='100' step='5' value={change} onChange={e=>setChange(Number(e.target.value))}/></label></section>
 <section className='method'><h3>Go deeper when you need to.</h3><p>For completed Solana trades, review a single public wallet or up to five wallets side by side. Open the original two-wallet comparison to inspect entry and exit differences.</p><div className='actions'><Button variant='outline' onClick={onReview}>Review wallet trades</Button><Button variant='outline' onClick={onCompare}>Compare two wallets</Button></div><p>Holdings are entered manually, not imported from a wallet. Market quotes estimate value; they are not an executable sale price. This view does not reconstruct purchase history, track previous realized gains or provide a tax report.</p></section><footer><span>CopyCheck / Know where you stand.</span><a href='https://www.coingecko.com/en/api'>Built with CoinGecko API</a></footer></main></>;
}
