"use client";
import {useEffect,useState} from 'react';
import {ExternalLink,Copy} from 'lucide-react';
import {money} from '@/lib/analysis';
type Snapshot={fetchedAt:string;market:{pair:string;name:string;symbol:string;dex:string;price:number|null;liquidity:number|null;volume:number|null}|null};
export default function TokenMarket({token}:{token:string}){
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0),[copied,setCopied]=useState(false);
 useEffect(()=>{const controller=new AbortController();setSnapshot(null);setError('');setLoading(true);setCopied(false);fetch('/api/token-market?token='+encodeURIComponent(token),{signal:controller.signal}).then(async r=>{const data=await r.json() as Snapshot&{error?:string};if(!r.ok)throw new Error(data.error||'Market data unavailable.');setSnapshot(data);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Market data unavailable.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[token,refresh]);
 const market=snapshot?.market,url=market?'https://www.geckoterminal.com/solana/pools/'+encodeURIComponent(market.pair):null;
 return <section className='token-market' aria-label='Token and current market'><div className='token-market-heading'><div><span className='eyebrow'>SOLANA TOKEN</span><h3>{market?market.name+' '+(market.symbol?'('+market.symbol+')':''):'Token market'}</h3></div>{url&&<a className='dex-link' href={url} target='_blank' rel='noreferrer'>Open CoinGecko chart <ExternalLink size={16}/></a>}</div><div className='token-address-line'><code>{token}</code><button type='button' aria-label='Copy token address' onClick={()=>{navigator.clipboard.writeText(token).then(()=>setCopied(true)).catch(()=>setError('Could not copy. Select the address to copy it manually.'));}}><Copy size={15}/>{copied?'Copied':'Copy'}</button></div><p className='note'>Chart opens on GeckoTerminal by CoinGecko.</p>{loading?<p role='status'>Loading market snapshot…</p>:error?<p role='status'>{error}</p>:market?<><div className='token-market-stats'><div><span>Current price</span><strong>{money(market.price)}</strong></div><div><span>Pool reserves</span><strong>{money(market.liquidity)}</strong></div><div><span>24h pool volume</span><strong>{money(market.volume)}</strong></div></div><p className='note'>{market.dex} · Highest reported reserves among up to 20 returned matching pools. This may differ from the pool used for your trade.</p></>:<p>No matching pool was returned by CoinGecko. You can still copy the token address.</p>}<div className='token-market-footer'><span>CoinGecko API{snapshot?' · fetched '+new Date(snapshot.fetchedAt).toLocaleTimeString():''}</span><button type='button' disabled={loading} onClick={()=>setRefresh(x=>x+1)}>Refresh market</button></div><p className='note'>Current market snapshot, not your historical execution price. Refresh to update; prices are not guaranteed sale quotes.</p></section>;
}
