"use client";
import {useEffect,useRef,useState} from 'react';
import {Wallet,Download,Info,FlaskConical,Loader2,ExternalLink} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {short,percent,money} from '@/lib/analysis';
import {demoReview,validateReviewRequest,type ReviewReport} from '@/lib/review';
const today=()=>new Date().toISOString().slice(0,10),weekAgo=()=>new Date(Date.now()-6*86400000).toISOString().slice(0,10);
const dollars=(v:number|null)=>v===null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:2,maximumFractionDigits:2}).format(v);
export default function WalletReview({onCompare}:{onCompare:()=>void}){
 const [report,setReport]=useState<ReviewReport>(()=>demoReview()),[walletText,setWalletText]=useState(''),[from,setFrom]=useState(weekAgo()),[to,setTo]=useState(today()),[selected,setSelected]=useState(0),[token,setToken]=useState('demo-ORBIT'),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[configured,setConfigured]=useState<boolean|null>(null);
 const lock=useRef(false);
 const tradeSection=useRef<HTMLDivElement>(null),tradeDetail=useRef<HTMLElement>(null);
 const reveal=(target:HTMLElement|null)=>requestAnimationFrame(()=>target?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}));
 useEffect(()=>{fetch('/api/status',{cache:'no-store'}).then(r=>r.json() as Promise<{configured:boolean}>).then(r=>setConfigured(Boolean(r.configured))).catch(()=>setConfigured(null));},[]);
 const chosen=report.wallets[selected],position=chosen?.positions.find(p=>p.token===token);
 const setWallet=(i:number)=>{setSelected(i);setToken(report.wallets[i]?.positions[0]?.token||'');setFilter('all');reveal(tradeSection.current);};
 const run=async()=>{if(lock.current)return;const input={wallets:walletText.split(/[\s,]+/).map(x=>x.trim()).filter(Boolean),from,to};try{validateReviewRequest(input);}catch(e){setError((e as Error).message);return;}lock.current=true;setBusy(true);setError('');try{const response=await fetch('/api/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input),signal:AbortSignal.timeout(55000)});const body=await response.json() as ReviewReport & {error?:string};if(!response.ok)throw new Error(body.error||'Review could not be completed.');setReport(body);setSelected(0);setToken(body.wallets[0]?.positions[0]?.token||'');setFilter('all');}catch(e){setError(e instanceof Error?e.message:'Review failed.');}finally{lock.current=false;setBusy(false);}};
 const exportReport=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='copycheck-wallet-review-'+report.from+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const rows=(chosen?.positions||[]).filter(p=>filter==='all'||filter==='closed'&&p.eligible||filter==='review'&&!p.eligible||filter==='losses'&&p.pnl!==null&&p.pnl<0);
 return <><main>
 <div className='heading'><div><div className='eyebrow'>A CLOSER LOOK AT YOUR OWN TRADES</div><h1>Start with your wallet.</h1><p>See which closed trades made or lost money. Add other wallets when a comparison helps.</p></div><div className='data-brand'><a href='https://www.coingecko.com/en/api' target='_blank' rel='noreferrer'><span>Built with</span><img src='/coingecko-api-logo.svg' alt='CoinGecko API' width='200' height='35'/></a><span className='pill'>Solana</span></div></div>
 <form className='compare-box' onSubmit={e=>{e.preventDefault();void run();}}><label className='wallet-input-label'><span><Wallet size={16}/>Public wallet addresses</span><textarea value={walletText} onChange={e=>setWalletText(e.target.value)} placeholder={'Paste your Solana wallet address\nOptional: add up to four more, one per line'} rows={3} maxLength={230} disabled={busy} required spellCheck={false}/></label><p className='note'>Start with your own trading wallet. You can add another wallet you use or a public wallet you want to study. You choose the list; no copying relationship is assumed.</p><div className='dates'><label>From<Input aria-label='Review start date' type='date' value={from} max={to||today()} onChange={e=>setFrom(e.target.value)} disabled={busy} required/></label><label>To<Input aria-label='Review end date' type='date' value={to} min={from} max={today()} onChange={e=>setTo(e.target.value)} disabled={busy} required/></label><Button type='submit' disabled={busy}>{busy?<><Loader2 className='animate-spin'/>Reading trades…</>:'Review wallets'}</Button><span className='status'>{configured===true?'Live data connected':configured===false?'Live access needs an API key':'Checking live access'}</span></div><div className='form-footer'><span>Read-only · 1–5 wallets · UTC dates · 90-day maximum</span><Button type='button' variant='ghost' disabled={busy} onClick={()=>{const r=demoReview();setReport(r);setSelected(0);setToken(r.wallets[0].positions[0].token);setFilter('all');setError('');}}><FlaskConical size={15}/>Try an example</Button></div><p className='privacy-note'>Reviewing sends the entered public addresses to CoinGecko. No wallet connection or signing.</p></form>
 {error&&<div className='error-banner' role='alert'><strong>Review not completed.</strong> {error}<p>The previous {report.mode==='demo'?'fictional example':'successful report'} remains below.</p></div>}
 <div className='demo-banner'><Info size={17}/><span>{report.mode==='demo'?<><strong>Fictional three-wallet example.</strong> Real review logic; no actual holdings or performance implied.</>:<><strong>Observed CoinGecko wallet trades.</strong> Each wallet is reviewed independently; these are not copying matches.</>}</span><small>{report.mode==='demo'?'DEMO DATA':'LIVE RESPONSE'}</small></div>
 <div className='review-heading'><h2>Wallets at a glance</h2><div className='actions'><span className='status'>{report.from} — {report.to} · UTC</span><Button size='sm' variant='outline' onClick={exportReport}><Download size={14}/>Export review</Button></div></div>
 <section className='panel wallet-overview'><div className='review-table-scroll'><table><thead><tr><th>Wallet</th><th>Closed tokens</th><th>Excluded tokens</th><th>Gross dollar result</th><th>Return on recorded buys</th><th>Trades</th></tr></thead><tbody>{report.wallets.map((w,i)=><tr className={'wallet-row '+(i===selected?'selected':'')} key={w.wallet} onClick={()=>setWallet(i)}><td><button className='wallet-choice' onClick={e=>{e.stopPropagation();setWallet(i);}} aria-pressed={selected===i}>{report.mode==='demo'?w.wallet:short(w.wallet)}</button></td><td>{w.closedCount}</td><td>{w.excludedCount}</td><td className={w.pnl!==null&&w.pnl<0?'follower':'leader'}>{dollars(w.pnl)}</td><td>{percent(w.returnPct)}</td><td><button className='wallet-choice view-trades' onClick={e=>{e.stopPropagation();setWallet(i);}} aria-label={'View buys and sells for '+(report.mode==='demo'?w.wallet:short(w.wallet))}>View buys &amp; sells ↓</button></td></tr>)}</tbody></table></div><div className='panel-foot'>Click a wallet row or View buys & sells to jump to its tokens and transactions. Same UTC window, independent results. Dollar totals use eligible closed tokens only. Different wallets may trade different tokens and sizes; this is not a skill ranking.</div></section>
 {chosen&&<><div className='review-heading wallet-detail-title'><h2>{report.mode==='demo'?chosen.wallet:short(chosen.wallet)} <small>{chosen.positions.length} tokens returned</small></h2></div>{chosen.error&&<div role='alert' className='error-banner'>{chosen.error} No result was inferred for this wallet.</div>}{(!chosen.coverage.complete||chosen.coverage.skipped>0)&&!chosen.error&&<p className='coverage'>History is incomplete or contains unusable records. Returns and dollar results are withheld for this wallet. Try a shorter date range.</p>}
 <div className='metrics'><section><span>Gross result · closed tokens</span><strong className={chosen.pnl!==null&&chosen.pnl<0?'follower':'leader'}>{dollars(chosen.pnl)}</strong><p>{chosen.closedCount} eligible tokens · before fees</p></section><section><span>Recorded buys / sales</span><strong className='review-cash'>{dollars(chosen.spent)} / {dollars(chosen.received)}</strong><p>Across those same eligible closed tokens</p></section><section><span>Positive / negative results</span><strong>{chosen.wins??'—'} / {chosen.losses??'—'}</strong><p>Breakeven tokens count as neither</p></section></div>
 <div className='review-highlights'><p><span>Highest dollar result</span><strong>{chosen.best?chosen.best.label+' · '+dollars(chosen.best.pnl):'Unavailable'}</strong></p><p><span>Lowest dollar result</span><strong>{chosen.worst?chosen.worst.label+' · '+dollars(chosen.worst.pnl):'Unavailable'}</strong></p></div>
 <div className='workspace wallet-trades-section' ref={tradeSection}><section className='panel'><div className='panel-heading'><h2>{report.mode==='demo'?chosen.wallet:short(chosen.wallet)} · tokens</h2><label className='review-filter'>Show <select aria-label='Filter reviewed trades' value={filter} onChange={e=>setFilter(e.target.value)}><option value='all'>All returned tokens</option><option value='closed'>Eligible closed tokens</option><option value='losses'>Losses</option><option value='review'>Needs review</option></select></label></div><div className='review-table-scroll'><table><thead><tr><th>Token</th><th>Gross result</th><th>Return</th><th>Status</th></tr></thead><tbody>{rows.map(p=><tr key={p.token} className={p.token===token?'selected':''}><td><button className='wallet-choice' onClick={()=>{setToken(p.token);reveal(tradeDetail.current);}}>{p.label}</button></td><td className={p.pnl!==null&&p.pnl<0?'follower':'leader'}>{dollars(p.pnl)}</td><td>{percent(p.returnPct)}</td><td><span className='chip'>{p.eligible?'Closed':!chosen.coverage.complete||chosen.coverage.skipped?'History incomplete':p.status==='unknown'?'Unknown basis':p.status==='multiple'?'Repeated trades':p.status==='partial'?'Partial exit':'Open'}</span></td></tr>)}</tbody></table></div>{!rows.length&&<div className='empty'>No tokens match this view. An empty response does not establish that the wallet never traded.</div>}<div className='panel-foot'>Open, partial, repeated and uncertain positions are excluded from dollar and return totals.</div></section>
 <aside className='panel detail wallet-trade-detail' ref={tradeDetail}>{position?<><div className='panel-heading'><h2>{position.label} · buys &amp; sells</h2></div><div className='insight'><h3>{position.eligible?dollars(position.pnl)+' before fees': 'Result withheld'}</h3><p>{position.reason}</p></div><div className='review-position'><dl><div><dt>Observed buy USD</dt><dd>{dollars(position.spent)}</dd></div><div><dt>Observed sell USD</dt><dd>{dollars(position.received)}</dd></div><div><dt>Average entry</dt><dd>{money(position.entry)}</dd></div><div><dt>Average exit</dt><dd>{money(position.exit)}</dd></div></dl><p className='note'>Only an eligible closed position has a calculated return. These fills do not establish current holdings or portfolio P&amp;L.</p><h3 className='evidence-title'>Transactions behind the result</h3><div className='evidence'>{position.trades.map(t=><div className='evidence-row' key={t.id}><div><strong>{t.side==='buy'?'Bought':'Sold'} · {dollars(t.usd)}</strong><small>{t.quantity.toLocaleString('en-US',{maximumSignificantDigits:7})} tokens · {new Date(t.time).toISOString().replace('T',' ').replace('.000Z',' UTC')}</small></div>{report.mode==='live'?<a href={'https://solscan.io/tx/'+encodeURIComponent(t.tx)} target='_blank' rel='noreferrer'>Tx <ExternalLink size={12}/></a>:<span className='note'>Synthetic</span>}</div>)}</div>{report.mode==='live'&&<p className='address'>Token: {position.token}</p>}</div></>:<div className='empty'>No trades are available to display for this wallet in the selected period. Check the dates or any history error above.</div>}</aside></div></>}
 <section id='method' className='method'><h3><Info size={18}/>A trade review, not a full wallet balance sheet.</h3><p>Each wallet stands on its own. There is no 30-minute copying rule in this view. CopyCheck groups swaps by exact token address and calculates results only for a single observed position whose buys and sells reconcile. It withholds results for incomplete history, missing cost basis, uncertain ordering, partial exits and repeated round trips.</p><p>Gross dollar result = recorded sales − recorded buys. Return on recorded buys = (total recorded sales ÷ total recorded buys − 1) × 100 for the same eligible closed tokens. This is not the equal-weight return used in the two-wallet copied-trade view, and it is not a portfolio return.</p><p>Five wallets is a request limit to keep a first review manageable, not an analytical requirement. Wallets are shown in the order you enter them. Each has a five-page history limit per 30-day segment. Transfers, prior inventory, unsupported venues, gas, tips and bot fees can change the actual result. CoinGecko supplies trades; CopyCheck computes the review.</p><Button variant='outline' onClick={onCompare}>Open the two-wallet entry / exit breakdown</Button></section><footer><span>CopyCheck / Start with your trades.</span><a href='https://www.coingecko.com/en/api' target='_blank' rel='noreferrer'>Built with CoinGecko API</a></footer></main></>;
}

